### ISSUE TITLE
wrong sql

### ISSUE THREAD

**Issue by BobRam** [dbmail/dbmail#111] opened 2021-04-20 21:13 UTC
Hi,

dbmail 3.2.3, fresh install with postgresql.

Error:

ERROR:  syntax error at or near "(" at character 171

SELECT message_idnr FROM dbmail_messages m 
LEFT JOIN dbmail_physmessage p ON m.physmessage_id=p.id 
WHERE mailbox_idnr = $1 AND status IN ($2,$3) AND m.message_idnr IN (2 (MODSEQ 3)) AND p.internal_date > '2021-01-22 00:00:00'
ORDER BY message_idnr

it seems wrong sql generated, (what is MODSEQ ?) i think "IN (2, 3) " will be better

**Comment by alan-hicks** [comment] 2021-04-21 09:31
This relates to CONDSTORE rfc7162.
MODSEQ is an IMAP command and shouldn't appear in SQL so this is a bug.

**Comment by CozC** [comment] 2021-04-21 09:57
Salve,

Most probably is related to dbmail_mailbox_ids_as_string and the call of  
the function in maibox_search (dm_mailbox.c).
The aforementioned function is used in imap response, with one exception  
in mailbox_search, and indeed is related to condstore.

It is not an easy fix, maybe it may work to drop CONDSTORE in IMAP  
Capability (dbmail.conf) in order to avoid the issue until the issue will  
be fixed.

-- 
Cosmin Cioranu

**Comment by alan-hicks** [comment] 2021-04-21 13:25
I've looked at this and the bug appears to have been there since the beginning, so I'm guessing something must have evolved with a new client to prod this bug after so many years.

dbmail_mailbox_ids_as_string is called in two places

- sorted_search_enter in imapcommands.c
where it appears to be used as an imap command and probably useful

- mailbox_search in dm_mailbox.c
where it's used to generate SQL and (MODSEQ %) is causing the error

It looks straightforward to add a flag to add MODSEQ for the IMAP command and omit it for the SQL one.

I'm unable to reproduce with any of my email clients and not familiar with CONDSTORE. It would be helpful to know what action and mail client is triggering this so it can be tested.

**Comment by BobRam** [comment] 2021-04-21 13:47
It happens on almost empty database - one account and one message arrived, than windows 10 client make imap requiest...

**Comment by alan-hicks** [comment] 2021-04-26 10:41
Thanks for confirming it's Windows 10 with any messages @BobRam. All clients I've checked including kmail, squirrelmail and roundcube use local cache for searching and so avoid this bug.

This appears to be a simple fix so will get this out asap.

**Comment by alan-hicks** [comment] 2021-04-26 16:38
I've created pull request #112, but the C/C++ CI / build has failed on an unrelated issue pulling in libgmime.
It builds and runs successfully on FreeBSD. Are there any known issues with gmime or libssl? I notice the pull request for gmime3 appears to have stalled, does that upgrade need to happen before this?

**Comment by CozC** [comment] 2021-04-26 17:18
It shouldn't happen. A few days I have compiled everything into a rpm  
(centos 7) and everything went ok (sqlite, mysql, posgress + ldap driver),  
no changes whatsoever.

The issue most likely is due to the testing environment from github (maybe  
something needs to be changed, I bet it ccpp.yaml using libssl1.0-dev it  
should have been libssl-dev)
As for gmime3, the stalled PR is due to some requests Paul has made and  
the have never been implemented. Unfortunately gmime3 is far different  
 from gmime 2 and changes made since then are somehow incompatible so the  
PR needs to be reevaluated.

As for your PR ia have made a PR Request in an attempt to mitigate the  
libssl issue.





On Mon, 26 Apr 2021 19:38:19 +0300, Alan Hicks ***@***.***>  
wrote:

>
> I've created pull request #112, but the C/C++ CI / build has failed on  
> an unrelated issue pulling in libgmime.
> It builds and runs successfully on FreeBSD. Are there any known issues  
> with gmime or libssl? I notice the pull request for >gmime3 appears to  
> have stalled, does that upgrade need to happen before this?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Closed** 2021-04-26 17:21 UTC

**Comment by CozC** [comment] 2021-04-26 17:26
synced all dbmail main repo with mine and run the build, everything is ok.


On Mon, 26 Apr 2021 20:17:56 +0300, Cosmin CIORANU  
***@***.***> wrote:

> It shouldn't happen. A few days I have compiled everything into a rpm  
> (centos 7) and everything went ok (sqlite, mysql, >posgress + ldap  
> driver), no changes whatsoever.
> The issue most likely is due to the testing environment from github  
> (maybe something needs to be changed, I bet it >ccpp.yaml using  
> libssl1.0-dev it should have been libssl-dev)
> As for gmime3, the stalled PR is due to some requests Paul has made and  
> the have never been implemented. Unfortunately >gmime3 is far different  
> from gmime 2 and changes made since then are somehow incompatible so the  
> PR needs to be >reevaluated.
>
> As for your PR ia have made a PR Request in an attempt to mitigate the  
> libssl issue.
>
>
>
>
>
> On Mon, 26 Apr 2021 19:38:19 +0300, Alan Hicks  
> ***@***.***> wrote:
>
>>
>> I've created pull request #112, but the C/C++ CI / build has failed on  
>> an unrelated issue pulling in libgmime.
>> It builds and runs successfully on FreeBSD. Are there any known issues  
>> with gmime or libssl? I notice the pull request for >>gmime3 appears to  
>> have stalled, does that upgrade need to happen before this?
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>
>
>
> --Cosmin Cioranu



-- 
Cosmin Cioranu
