### ISSUE TITLE
dbmail-imapd hangs randomly when only a single client is connected

### ISSUE THREAD

**Issue by awheeler** [dbmail/dbmail#37] opened 2020-04-08 17:28 UTC
Testing with a single client connected to a dbmail-imapd mailbox with a few hundred folders
One folder has around 600 messages.
When iterating through the list of messages in that folder, only fetching BODYSTRUCTURE results in random hangs.

These hangs resolve if another client connects and issues commands to dbmail.
This doesn't seem to happen when an strace is attached to the dbmail-imapd process.

This is against dbmail-3.2.3 with some patches, but I may build a plain 3.2.3 and see if it behaves the same.

**Comment by awheeler** [comment] 2020-04-08 17:29
Here's the python code I wrote to test this:
```
#!/usr/bin/python

import imaplib

username="username"
password="password"
host="imap.host"

M = imaplib.IMAP4(host)
M.login(username,password)
lst = M.list()
assert lst[0]=='OK'
for mbx in lst[1]:
    print "Mailboxes:",mbx

def process(m):
    print "m=",m
    res = M.recent()
    print res


(response, counts) = M.select('INBOX')
count = int(counts[0])
print count
for num in range(1,count+1):
        print 'Processing :', num
        typ, data = M.fetch(num,'(BODYSTRUCTURE)')
M.close()
M.logout()
```

**Comment by awheeler** [comment] 2020-04-08 17:36
The last thing logged with logging set to 511 is:

```
Apr 08 17:30:57 imapd.host dbmail-imapd[1185]: [0xa8af20] Debug:[clientbase] ci_write(+347): [0xbf0000] S > [931/931:* 474 FETCH (BODYSTRUCTURE (("text" "plain" ("charset" "UTF-8" "") NIL NIL "8bit" 213 9 NIL NIL NIL NIL)("message" "delivery-status" ("charset" "UTF-8" "") NIL NIL "8bit" 407 NIL NIL NIL NIL)("text" "rfc822-headers" NIL NIL NIL "8bit" 2788 35 NIL ("attachment" NIL) NIL NIL)("message" "rfc822" NIL NIL NIL "8bit" 5868 ("Sat, 29 Feb 2020 06:41:49 -0500" "RE: ..." (("Display Name" NIL "localpart" "domain.org"))(("Display Name" NIL "localpart" "domain.org"))(("Display Name" NIL "localpart" "domain.org"))((NIL NIL "sender_localpart" "sender_domain.org")) NIL NIL NIL "<1471825573.41215024.1582976509256.JavaMail.nobody@foo.bar.com>")("text" "html" ("charset" "UTF-8") NIL NIL "quoted-printable" 3082 55 NIL NIL NIL NIL) 88 NIL ("attachment" NIL) NIL NIL) "report" ("boundary" "------------I305M09060309060P_409715830004400") NIL NIL NIL))]
```

**Comment by CozC** [comment] 2020-04-08 17:45
Salve,

Weird bug. I have seen in the past random hangs, but I thought is was  
always due to database issues related with some longer queries being run.
what are you describing is entirely new issue. Give the fact that client  
is doing that folder state (I was mentioning earlier) on each folder I  
would go towards a memory issues. But, giving the fact it "unhungs" if  
another client is connected that points to some thread  being stuck on  
something and aborts operation upon new connection

I have to check it out the issue. Unfortunately I do not have so many  
folders in my test environment (I have to replicate it somehow )
I will test on the latest trunk version

Keep in touch.



On Wed, 08 Apr 2020 20:28:15 +0300, Alex Wheeler  
<notifications@github.com> wrote:

>
> Testing with a single client connected to a dbmail-imapd mailbox with a  
> few hundred folders, and around 600 messages in a single folder.  
> Iterating >through the list of messages, fetching BODYSTRUCTURE results  
> in random hangs.
> These hangs resolve if another client connects and issues commands to  
> dbmail.
> This is against dbmail-3.2.3 with some patches, but I'll build a plain  
> 3.2.3 and see if it behaves the same.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by awheeler** [comment] 2020-04-08 17:47
I don't think the folders are relevent, as it's just iterating through the messages when it hangs.

**Comment by awheeler** [comment] 2020-04-08 17:56
I think the dbmail_iconv is a red herring, as it's just logging the atexit calls

**Comment by CozC** [comment] 2020-04-08 18:05
I just started the test... It run until the end...
If you are thinking that is the issue, then it's related to the data. In  
production environment I have seen some issue related to UTF-8 conversions  
which went strait ti SQLException. In the past I have put a monitor which  
did a hard restart if DBMail did not respond in 2-3 seconds. But those  
issue I have found them mostly on a Centos 6 environment, in Centos 7, I  
did not observe such a behavior.

You may find this using valgrind or gdb (hopefully there will be an  
assertion or something)

On Wed, 08 Apr 2020 20:56:15 +0300, Alex Wheeler  
<notifications@github.com> wrote:

>
> I think the dbmail_iconv is a red herring, as it's just logging the  
> atexit calls
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by awheeler** [comment] 2020-04-08 18:08
I sometimes have to run it several times, as the hang is random.  I'll try to replicate with on-the-fly data.

**Comment by CozC** [comment] 2020-04-08 19:48
Hey,

I did not seen the issue yet, but I used the latest version with all  
patches  (a little bit different than yours),  
https://github.com/nbeta-git/dbmail/tree/wFork
Still checking.

The php version

`
echo "\nConnecting...";
$host="{host}";
$user="user";
$pass="pass";
$mbox=imap_open($host,$user,$pass);

$list = imap_list($mbox,$host,"*");
imap_close($mbox);
if (is_array($list)) {
     foreach ($list as $key => $val) {
		echo "\n[.] Opening mbox to $val... ";
		$mbox=imap_open($val,$user,$pass);
		$MC=imap_check($mbox);
         $MN=$MC->Nmsgs;
		if ($MN>0){
			echo "fetching...$MN";
			$overview = imap_fetch_overview($mbox,"1:$MN",0);
			$i=0;
			while( list($key,$val) = each($overview)) {
				$i++;
				echo "\n\t $i. parse ".$val->uid."...";
				//$s= imap_fetchheader($mbox,$val->uid, FT_UID );
				//echo "header: ".strlen($s)." size, ";
				$fs= imap_fetchstructure ($mbox,$val->uid, FT_UID );
				echo "fs: ".strlen(var_export($fs,true))." size";
				//did not care about actual result, followed only the server sql
				$fb=imap_fetchbody($mbox,$val->uid,2,FT_UID);
				echo "fb: ".strlen(serialize($fb))." size";
				var_dump($fb);
			}
		}else{
			echo "0";
		}
		imap_close($mbox);
		continue;
     }
}
return;

`


On Wed, 08 Apr 2020 21:08:23 +0300, Alex Wheeler  
<notifications@github.com> wrote:

>
>
> I sometimes have to run it several times, as the hang is random.  I'll  
> try to replicate with on-the->fly data.
>
>
>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.[]
>
>



-- 
Cosmin Cioranu

**Comment by CozC** [comment] 2020-04-08 19:51
I did use the python and php in order to replicate the issue. I was  
wondering about the FD patch?! I did not get it quite 100%... but it worth  
a look. (just a nightly thought)



On Wed, 08 Apr 2020 22:48:16 +0300, Cosmin CIORANU  
<cosmin.cioranu@gmail.com> wrote:

> Hey,
>
> I did not seen the issue yet, but I used the latest version with all  
> patches  (a little bit different than yours),  
> https://github.com/nbeta-git/dbmail/tree/wFork
> Still checking.
>
> The php version
>
> `
> echo "\nConnecting...";
> $host="{host}";
> $user="user";
> $pass="pass";
> $mbox=imap_open($host,$user,$pass);
>
> $list = imap_list($mbox,$host,"*");
> imap_close($mbox);
> if (is_array($list)) {
>      foreach ($list as $key => $val) {
> 		echo "\n[.] Opening mbox to $val... ";
> 		$mbox=imap_open($val,$user,$pass);
> 		$MC=imap_check($mbox);
>          $MN=$MC->Nmsgs;
> 		if ($MN>0){
> 			echo "fetching...$MN";
> 			$overview = imap_fetch_overview($mbox,"1:$MN",0);
> 			$i=0;
> 			while( list($key,$val) = each($overview)) {
> 				$i++;
> 				echo "\n\t $i. parse ".$val->uid."...";
> 				//$s= imap_fetchheader($mbox,$val->uid, FT_UID );
> 				//echo "header: ".strlen($s)." size, ";
> 				$fs= imap_fetchstructure ($mbox,$val->uid, FT_UID );
> 				echo "fs: ".strlen(var_export($fs,true))." size";
> 				//did not care about actual result, followed only the server sql
> 				$fb=imap_fetchbody($mbox,$val->uid,2,FT_UID);
> 				echo "fb: ".strlen(serialize($fb))." size";
> 				var_dump($fb);
> 			}
> 		}else{
> 			echo "0";
> 		}
> 		imap_close($mbox);
> 		continue;
>      }
> }
> return;
>
> `
>
>
> On Wed, 08 Apr 2020 21:08:23 +0300, Alex Wheeler  
> <notifications@github.com> wrote:
>
>>
>>
>> I sometimes have to run it several times, as the hang is random.  I'll  
>> try to replicate with on-the->fly data.
>>
>>
>>
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub, or unsubscribe.[]
>>
>>
>
>
>


-- 
Cosmin Cioranu

**Comment by awheeler** [comment] 2020-04-08 20:03
Gotcha, yeah, I may check that code too...what's the easiest way to add a test to dbmail?  Is there documentation on the testing framework?

**Comment by CozC** [comment] 2020-04-08 20:21
There 2 ways,

1. Define a test case in test folder, add it into the test/makefile.am and  
run `autoreconf --install`
This tests are quite heavy on writing them, but are worth the effort.
In order to run them you need to configure with the `--with-check` flag  
and have check-devel installed (Centos variant)
and then `make check`
Another way is to import the project into netbeans (or another IDE), and  
run various code by hand. I usually, because I'm lazy, rig one of the  
tests and run my own code :P

2. The other way is to add it in test-scripts. Those test, as far as I  
know can be run only by hand, there are various tests and use-cases there  
(pyhon, php, ruby).

Hope it helps.

On Wed, 08 Apr 2020 23:03:30 +0300, Alex Wheeler  
<notifications@github.com> wrote:

>
> Gotcha, yeah, I may check that code too...what's the easiest way to add  
> a test to dbmail? Is there documentation on the testing framework?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by awheeler** [comment] 2020-04-08 20:32
Perfect, thank you!

**Comment by awheeler** [comment] 2020-04-09 19:05
So this doesn't appear to be a bug in the code, per se, or it's even harder to trigger, bc when I run dbmail-imapd (same exact rpm) in a clean docker environment, connected to the same mysql database, it doesn't happen.

**Comment by CozC** [comment] 2020-04-23 10:31
So, it seems to be related to libzdb issue (related to compilation flags)  
or mysql instance(maybe some running parameters) . I'm glad that is not  
directly linked to code (or doesn't seem to). If you have the spec used to  
build the rpm can it be shared?


On Thu, 09 Apr 2020 22:05:24 +0300, Alex Wheeler  
<notifications@github.com> wrote:

>
> So this doesn't appear to be a bug in the code, per se, or it's even  
> harder to trigger, bc when I run dbmail-imapd (same exact rpm) in a  
> clean docker >environment, connected to the same mysql database, it  
> doesn't happen.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by CozC** [comment] 2020-05-01 18:34
Salve I have found that some newer Outlook clients (2019) throw some errors on something that might be related to this issue.  I'm still investigating and it is a little bit challenging due the way logs are stored and offered by Outlook.
Did you encountered something similar? Or your issues were related to Java Client only?

**Comment by CozC** [comment] 2020-05-03 11:14
Salve, I have manage to stumble upon the issue using the python tester. I started poking round the issue and I found out the the issue disappears when I reset the default socket timeout of python sockets using 
`
import socket
socket.setdefaulttimeout(15)  # In seconds
`

Also the issue is pregnant when used in conjunction with valgrind which made me believe it is related to some network synchronizations.

**Comment by awheeler** [comment] 2020-05-06 13:57
Oh, very nice!  I can still get you that RPM spec if you like.

**Comment by CozC** [comment] 2020-05-06 16:37
Thanks. 
Also @LOTRg  pushed an update related to RPM spec files
On a side note, I plan to deliver rpm on the next release, which I hope it will be soon.

**Comment by cncioranu** [comment] 2020-05-11 20:06
Closing, no activity, tested on centos 6, 7, single client, multiple clients.
Also checked manually (via telnet) and using various implementation and the bug cannot be reproduced (unless the python defaulttimeout is not set)
So Closing.

**Comment by CozC** [comment] 2020-05-12 09:22
Upon investigating some issues related to performance (at connection time) I stumble upon the  issue. Investigating further I have found that is related to the writing event (I do not know why, still searching). Safe to say that after adding the fix, the problem went away (it was not related to timeout issue of the python library)
Please find the commit [here ](https://github.com/cncioranu/dbmail/commit/bf3705a70f6a3d1c00c1e4e2d34e918f8c075fd9)
The patch dues fix the issue, but I have some issues (logically) related to the situation when connection is ended.
The libevent documentation does state that event_add(ev) subsequent event_add(ev) does not duplicate the event, but what happens when the connection closes.

For now it will work. I would like to know your thoughts on the matter and if the patch works for you.

**Comment by CozC** [comment] 2020-05-15 17:44
No more activity, closing.

**Closed by CozC** 2020-05-15 17:44 UTC
Labels: bug
