### ISSUE TITLE
Empty headers / missing information Thunderbird / DBMail 3.5.x

### ISSUE THREAD

**Issue by sthoefer** [dbmail/dbmail#285] opened 2024-09-09 10:11 UTC
I have 80 GB of mail data in Postgres 15 (a clone of a productive DBMail 3.2.x database). On the client side, I use Thunderbird 115.15.0 . While doing a few memory tests on a new Debian server with DBMail trunk/main, I encountered the following strange behavior. At first, I thought, it was due to my using sanitizer in order to hunt down a couple of possible memory leaks, but then I removed sanitizer and started again from the beginning, and the behavior is still reproducible. I didn't find anything in the existing issues list that fits close, maybe issue #265 has something to do with this, but I'm not sure.

It goes like this:

1. First, I clone my database (remember: the source has been productive for more than 10 years, no problems there)

2. Before I start imapd, I use 'dbmail-util -ay' to fix a few things. There seem to be a few broken mails around, but with my fix posted in #284, dbmail-util continues and runs till the end. I am not sure whether all errors are fixed, indeed dbmail-util states after a couple of runs:

```
Nothing found searching for [<redacted email here>].
Nothing found searching for [<another redacted email here>].
Nothing found searching for [<and another one>].

Maintenance done. Errors were found but not fixed due to failures.
Please check the logs for further details, turning up the trace level as needed.

```

Debug level is 255, but not more information than this is available. But this is not really the problem, indeed the problem also occurs if I don't use dbmail-util as step 2.

3. Then I start imapd. I connect to a (large) mail account (using IMAP) and start downloading the mail. This works ok. Everything looks fine. There are no strange mails visible, everything is where it should be and looks ok.

4. Then I remove the mail account from Thunderbird (I explicitely choose "remove message data", just to be sure), close Thunderbird, start Thunderbird and (again) connect to the mail account. Thunderbird now downloads the mails again.

5. Now the funny thing is this: after this second download of the complete account, some mails (not in all folders, just some, but then for about 30-50% of those mails in this folder) appear to have insufficient header information. In the folder listing in Thunderbird, there is no subject or date or from/to address for those mails (they are kind of an empty line in the folder listing). However, if I click on those mails, Thunderbird shows me all information. So I guess the mails themselves are ok in the database, including header information, but at some point during the initial download of the mails after account connection, the header information appears to not having been available for some mails (again: not all of the mails, just some).

When I start again with step 1 (cloning the database), everything starts anew. First everything is ok, then after the second connect/download, several mails in some folders are mutilated. Things I checked are:

* all mails missing header information in the listing belong in the folder they are in
* no mails are missing (the number of mails is correct), only the header information in the folder listing isn't there
* no mails are corrupt, as far as I can tell
* no mails are duplicated/move/copied/whatever
* there is no rule (like date or sender/receiver) to what mails are missing information in the listing; only that either a lot of mails in a folder are missing information, or none. Also, the size of the folder (number of mails in it) seems to not play a role.

I have no clue as to where to start debugging this. Any pointer or direction you might be giving me would be highly appreciated.

**Comment by CozC** [comment] 2024-09-09 10:30
SalveMy guess(is just a wild guess) is the seq field between mailbox is greater then the seq of the message. Might be a validation here when getting the headers. When such a mail occurs please check if this is the case.CC @ gmail
-------- Original message --------From: Stefan ***@***.***> Date: 9/9/24  13:12  (GMT+02:00) To: dbmail/dbmail ***@***.***> Cc: Subscribed ***@***.***> Subject: [dbmail/dbmail] Empty headers / missing information Thunderbird / DBMail 3.5.x (Issue #285) 
I have 80 GB of mail data in Postgres 15 (a clone of a productive DBMail 3.2.x database). On the client side, I use Thunderbird 115.15.0 . While doing a few memory tests on a new Debian server with DBMail trunk/main, I encountered the following strange behavior. At first, I thought, it was due to my using sanitizer in order to hunt down a couple of possible memory leaks, but then I removed sanitizer and started again from the beginning, and the behavior is still reproducible. I didn't find anything in the existing issues list that fits close, maybe issue #265 has something to do with this, but I'm not sure.
It goes like this:


First, I clone my database (remember: the source has been productive for more than 10 years, no problems there)


Before I start imapd, I use 'dbmail-util -ay' to fix a few things. There seem to be a few broken mails around, but with my fix posted in #284, dbmail-util continues and runs till the end. I am not sure whether all errors are fixed, indeed dbmail-util states after a couple of runs:


Nothing found searching for [<redacted email here>].
Nothing found searching for [<another redacted email here>].
Nothing found searching for [<and another one>].

Maintenance done. Errors were found but not fixed due to failures.
Please check the logs for further details, turning up the trace level as needed.


Debug level is 255, but not more information than this is available. But this is not really the problem, indeed the problem also occurs if I don't use dbmail-util as step 2.


Then I start imapd. I connect to a (large) mail account (using IMAP) and start downloading the mail. This works ok. Everything looks fine. There are no strange mails visible, everything is where it should be and looks ok.


Then I remove the mail account from Thunderbird (I explicitely choose "remove message data", just to be sure), close Thunderbird, start Thunderbird and (again) connect to the mail account. Thunderbird now downloads the mails again.


Now the funny thing is this: after this second download of the complete account, some mails (not in all folders, just some, but then for about 30-50% of those mails in this folder) appear to have insufficient header information. In the folder listing in Thunderbird, there is no subject or date or from/to address for those mails (they are kind of an empty line in the folder listing). However, if I click on those mails, Thunderbird shows me all information. So I guess the mails themselves are ok in the database, including header information, but at some point during the initial download of the mails after account connection, the header information appears to not having been available for some mails (again: not all of the mails, just some).


When I start again with step 1 (cloning the database), everything starts anew. First everything is ok, then after the second connect/download, several mails in some folders are mutilated. Things I checked are:

all mails missing header information in the listing belong in the folder they are in
no mails are missing (the number of mails is correct), only the header information in the folder listing isn't there
no mails are corrupt, as far as I can tell
no mails are duplicated/move/copied/whatever
there is no rule (like date or sender/receiver) to what mails are missing information in the listing; only that either a lot of mails in a folder are missing information, or none. Also, the size of the folder (number of mails in it) seems to not play a role.

I have no clue as to where to start debugging this. Any pointer or direction you might be giving me would be highly appreciated.

**Comment by alan-hicks** [comment] 2024-09-09 12:34
I've come across this before, it appears to be when the header hasn't been fully cached.

You can see how caching works here:
https://dbmail.org/architecture/email-cache/

My current guess is with a heavily loaded database there's a timeout that causes caching to fail.

Nothing found searching for [email] just means those email addresses aren't associated with users in dbmail. You might want to check dbmail_aliases.

Messages and message lists use different tables so it's possible to see an empty subject or date in Thunderbird and have a complete original message available. It's unusual, but does happen.

The following counts the total number of messages you have;
```
SELECT
  count(messages.message_idnr)
FROM dbmail_messages as messages;
```
And these queries identify where a cache is missing
```
SELECT
  count(messages.message_idnr)
FROM dbmail_messages as messages
INNER JOIN dbmail_physmessage AS physmessage
ON physmessage.id = messages.physmessage_id
LEFT OUTER JOIN dbmail_referencesfield as referencesfield
ON referencesfield.physmessage_id = physmessage.id
WHERE referencesfield.id IS NULL;

SELECT
  count(messages.message_idnr)
FROM dbmail_messages as messages
INNER JOIN dbmail_physmessage AS physmessage
ON physmessage.id = messages.physmessage_id
LEFT OUTER JOIN dbmail_envelope as envelope
ON envelope.physmessage_id = physmessage.id
WHERE envelope.id IS NULL;

SELECT
  count(messages.message_idnr)
FROM dbmail_messages as messages
INNER JOIN dbmail_physmessage AS physmessage
ON physmessage.id = messages.physmessage_id
LEFT OUTER JOIN dbmail_header as header
ON header.physmessage_id = physmessage.id
AND header.headername_id = 
  (SELECT id from dbmail_headername
  WHERE headername = 'subject')
LEFT OUTER JOIN dbmail_headervalue as headervalue
ON headervalue.id = header.headervalue_id
WHERE headervalue.id IS NULL;

SELECT
  count(messages.message_idnr)
FROM dbmail_messages as messages
INNER JOIN dbmail_physmessage AS physmessage
ON physmessage.id = messages.physmessage_id
LEFT OUTER JOIN dbmail_header as header
ON header.physmessage_id = physmessage.id
AND header.headername_id = 
  (SELECT id from dbmail_headername
  WHERE headername = 'date')
LEFT OUTER JOIN dbmail_headervalue as headervalue
ON headervalue.id = header.headervalue_id
WHERE headervalue.id IS NULL;
```
There are various reasons a cache entry might be missing such as not being in a message although that would be unusual.

I'm planning on extending dbmail-utils to identify missing entries and re-caching them.

**Comment by hemml** [comment] 2024-09-09 12:42
Sometimes, I'm also have a similar problem -- some messages are not fetching correctly by IMAP (Apple Mail client). Sometimes I see no subject, sometimes one or more attachments are not downloaded, or no message body at all. In such cases I'm just moving the problematic message to another mail account and returning it back, this always fixes the problem. The dbmail server is used by many people in our institute, so I cannot experiment with debug levels or debug the code, sorry.

**Comment by sthoefer** [comment] 2024-09-17 14:24
When I run 'dbmail -ay' in gdb, I get this:

```
Thread 1 "dbmail-util" received signal SIGSEGV, Segmentation fault.
__memset_evex_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:224
224	../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S: Datei oder Verzeichnis nicht gefunden.
(gdb) up
#1  0x00007ffff7d79d40 in dbmail_message_init_with_string (
    self=self@entry=0x555555616600, 
    str=0x5555555ef230 ".stack.two-col.has-gutter .column {\r\n  max-width: 290px !important;\r\n  width: 290px !important;\r\n}\r\n=2Eie .stack.three-col.has-gutter .column,\r\n=2Eie .stack.has-gutter .narrow {\r\n  max-width: 188px !i"...) at dm_message.c:841
841			memset(fixdata, 0, sizeof(strlen(fixheader) + buflen + 1));
(gdb) up
#2  0x00007ffff7d7a028 in _mime_retrieve (self=self@entry=0x555555616600)
    at dm_message.c:502
502		self = dbmail_message_init_with_string(self,p_string_str(m));
(gdb) up
#3  0x00007ffff7d7a654 in _retrieve (self=self@entry=0x555555616600, 
    query_template=0x7ffff7daed30 "SELECT b.messageblk, b.is_header, %s FROM %smessageblks b JOIN %sphysmessage p ON b.physmessage_id=p.id WHERE b.physmessage_id = %lu ORDER BY b.messageblk_idnr") at dm_message.c:1088
1088		if ((self = _mime_retrieve(self)))
(gdb) up
#4  0x00007ffff7d7a8de in _fetch_full (self=0x555555616600)
    at dm_message.c:1144
1144		return _retrieve(self, query_template);
(gdb) up
#5  dbmail_message_retrieve (self=0x555555616600, physid=physid@entry=614658)
    at dm_message.c:1160
1160		self = _fetch_full(self);

```

**Comment by sthoefer** [comment] 2024-09-17 14:28
I just realized that this probably belongs in #284

**Comment by alan-hicks** [comment] 2024-09-17 18:17
Not sure what's going on here, I'll do some more checking.

**Comment by alan-hicks** [comment] 2024-10-25 15:37
Is this issue fixed with recent updates or is it still outstanding?

**Comment by alan-hicks** [comment] 2024-12-04 17:05
Closing as no feedback and all checks pass.

**Closed by alan-hicks** 2024-12-04 17:05 UTC
