### ISSUE TITLE
Some incoming mails lose their contents in dbmail 3.4.1 and later (github)

### ISSUE THREAD

**Issue by mayrk** [dbmail/dbmail#289] opened 2024-09-28 12:56 UTC
I run multiple installations of dbmail on FreeBSD 14.1 based servers.
On all servers i upgraded mysql to 9.0.1 some weeks ago.

I noticed on some if the hosts that a few mails are stored without any content except the main header.
When i look into dbmil_partlist and mimeparts i see inly record with is_header=1, but no bodies.
Some of these messages are distributed also to addresses that are not connected to the dbmail server so i know they have contents.

Digging in dbmail.err file i see SQLExceptions that "data" cannot be null.

Currently i have no idea where on the way to the blob_insert() function the content parts get lost or why.
I added some TRACE calls in dm_message.c to get the strlen() of 'buf' which is zero when in blob_insert().

Assuming a problem in parsing the mime parts i also tried gmime 3.2.15 (instead 3.2.7) as well as the dbmail version (3.5.x) 
from github.

I don't think it is an issue in mysql 9.0.1 ? The 'buf' seems to be empty before it can be written in the database ...
In need to setup a new testing host to see if an older version of mysql (< 8.4) makes any differene.

Most messages are processed without any errors and the content is shown in mail clients, so it is not easy to reproduce 
this behaviour with specific external senders ...

Any idea what else i can try to see what happens while parsing and storing the message parts ?

**Comment by CozC** [comment] 2024-09-28 13:05
I have found out that when a mail has an empty part ""(comming from mimeparys of the mail), the latest libzdb library convers the insert into null. On my installation i have converted the mimeparts table  to accept null (as a fast workaround).As a permanent workaround it should the code be ammendedHope it helpsCC @ gmail
-------- Original message --------From: mayrk ***@***.***> Date: 9/28/24  15:56  (GMT+02:00) To: dbmail/dbmail ***@***.***> Cc: Subscribed ***@***.***> Subject: [dbmail/dbmail] Some incoming mails lose their contents in dbmail 3.4.1 and later (github) (Issue #289) 
I run multiple installations of dbmail on FreeBSD 14.1 based servers.
On all servers i upgraded mysql to 9.0.1 some weeks ago.
I noticed on some if the hosts that a few mails are stored without any content except the main header.
When i look into dbmil_partlist and mimeparts i see inly record with is_header=1, but no bodies.
Some of these messages are distributed also to addresses that are not connected to the dbmail server so i know they have contents.
Digging in dbmail.err file i see SQLExceptions that "data" cannot be null.
Currently i have no idea where on the way to the blob_insert() function the content parts get lost or why.
I added some TRACE calls in dm_message.c to get the strlen() of 'buf' which is zero when in blob_insert().
Assuming a problem in parsing the mime parts i also tried gmime 3.2.15 (instead 3.2.7) as well as the dbmail version (3.5.x)
from github.
I don't think it is an issue in mysql 9.0.1 ? The 'buf' seems to be empty before it can be written in the database ...
In need to setup a new testing host to see if an older version of mysql (< 8.4) makes any differene.
Most messages are processed without any errors and the content is shown in mail clients, so it is not easy to reproduce
this behaviour with specific external senders ...
Any idea what else i can try to see what happens while parsing and storing the message parts ?

**Comment by alan-hicks** [comment] 2024-09-28 13:28
Is there a sample email you can provide for testing?

If it's arriving elsewhere it would be good to know what's causing the null mime part.

**Comment by mayrk** [comment] 2024-09-28 14:10
As far as i know so far what my colleagues told me it affects some mails from external laboratories with a list of samples which are planned for analysis (as excel file or csv file) and internal reports from our erp system with attached pdf files. 
Samples may contain confidential things bu i would not care if it helps for debugging.

Strange:

I tried to forward a copy of such messages (the complete ones) to my private host which runs dbmail 3.4.1 on mysql 9.0.1 
with gmime 3.2.7 und libzdb 3.4.0, but then the message is stored correctly with all of its contents including attachments
in dbmail ....

I start the query in the erp system and configured my private address as direct target. 
In this case the message is again empty.

It sems that the forwarded message or the server that received that copy fixes some contents in the mail.
I ould export the copy as EML file but these copy may not be able to reproduce the error ...

**Comment by mayrk** [comment] 2024-09-28 14:37
i created the erp report to produce some random text in the pdf file an message body. :-)

The "password" for the zip file is some quoted word here in the comment ... ;-)

[dbmail-sample-github-issue-289,eml.zip](https://github.com/user-attachments/files/17174746/dbmail-sample-github-issue-289.eml.zip)

**Comment by alan-hicks** [comment] 2024-09-28 15:13
Thanks for this. I've tried it and unfortunately all works as expected. I have an event to go to this evening so will continue looking tomorrow.

**Comment by alan-hicks** [comment] 2024-09-29 12:52
I'm struggling to re-create the same error as you, and all my github notifications have contents.

Your issue appears to be a mime part not identified/extracted on delivery. I'm using the same gmime 3.2.7 so I doubt it's that. I doubt libzdb has any impact as you've identified the mime part has zero length. I'm running libzdb 3.2.3 but there haven't been any changes that should affect this.

When inserting emails are you using dbmail-deliver or dbmail-lmtpd? Could you try both please.

I've tested them and they both work as expected.

I'm reluctant to change mime parts to allow nulls as that would accept bad data and go unnoticed. Email should never lose data.

**Comment by mayrk** [comment] 2024-09-29 14:36
Looking in postfix config in master.cf the transport is configured to use "lmtp" (dbmail-lmtpd, Port 24).
(Postfix => amavisd-new => Postfix => dbmail-lmtpd)

I tried to add a line in my master.cf to user dbmail-deliver ... as described in the README ...

but whatever i enter for user= i get a fatal error "pipe service dbmail-deliver requires privileged operation".
Postfix manual says not to use the root user or mail system owner for pipe commands ... **confused**
I tried "root", "nobody", myself, a new user "dbmail" ... always the same error ...

###

I am setting up a new server (or virtual machine) for testing with a clean and empty database.
Unfortunately mysql 8.1 ist no longer in freebsd ports collection.

The problem exists since the upgrade to the latest mysql version, but mysql was not the only thing that was upgraded on the servers that now have that problem ...

**Comment by alan-hicks** [comment] 2024-09-29 14:47
It shouldn't matter what database version you're using, dbmail only does simple selects and inserts.

What's needed is to find out what's causing a mime part to disappear. Maybe I should add extra debugging to track mime parts before they're inserted.

**Comment by alan-hicks** [comment] 2024-09-29 15:00
PS SQLite 3 is okay for testing.

**Comment by mayrk** [comment] 2024-09-29 15:52
Can i add some kind of dump file output of the message buffer/string after the LMTP QUIT command  ?

When the same message forwarded from another recipient to dbmail-lmtpd works as expected there must be 
something strange in the message ... 

The transport of both messages is the same ...
from Postfix(:SMTP) ==> amavisd-new(:10024) ==> Postfix(:10027) ==> dbmail-lmtp:localhost:24 ...

**Comment by alan-hicks** [comment] 2024-09-29 16:12
As Amavis is an email filter, could it be filtering out that mime part. Is there a log entry identifying what is removed?

**Comment by mayrk** [comment] 2024-09-29 16:54
Amavis does not change or remove any content. 
It it doesn't like some attachments, the whole message will be quarantined an will not be reinjected into postfix for delivery.
I tested it with "content_filter" settng disabled but no difference ... the mail is empty ...

Postfix log says 25974 for the size of the message, dbmail_physmessage=>messagesize says the same value ...
so i understand that the complete message arrived in the dbmail ?

The same message forwarded from another recipient also passes through amavis before it arrives dbmail-lmtpd ...

When i look at the mail source text in Thunderbird it looks like the main header content is repeated multiple times ...
The Part from Return-Path to Message-ID is for this sample 8 or 9 times in the source windows ...

**Comment by alan-hicks** [comment] 2024-09-29 17:26
Okay, I'll add debugging info to track details message and mime parts. Probably be ready tomorrow.

**Comment by alan-hicks** [comment] 2024-09-29 19:30
Okay, I'll add debugging info to track details message and mime parts. Probably be ready tomorrow.

**Comment by alan-hicks** [comment] 2024-09-29 19:37
Your samples make no sense! Having the same part_id is part of caching, indexed on the hash.
Your list shows headers the same as bodies. Empty bodies would have the same mime part, but different headers would have their own entry.
I'll add some extra debug code tomorrow to discover what's going on, you definitely shouldn't get what you're getting.

**Comment by CozC** [comment] 2024-09-30 05:25
Salve @mayrk 
I have checked also 3.4.1 with one message from of that has truncated your content. 
The results:
- the display of the message (attached)
- the message has been parsed into a null content (attached)

Now my setup has a hot patch: allow the `data` field to be null, otherwise I'll be getting the same result as you (all parts removed, because dbmail triggers an exception on insert and all processing is aborted). In the latest branch 3.5 I pushed an update that ignores those empty parts in order to move forward. 


![mail](https://github.com/user-attachments/assets/889403e5-da80-4b4f-be9c-ebb6a35a8aca)
![db](https://github.com/user-attachments/assets/2099de41-6491-4188-bee0-d8e2b7447e9d)

**Comment by mayrk** [comment] 2024-09-30 08:40
Greetings,

i modified the src/dm_message.c file as shown in the commit, recompiled dbmail and restarted the service dbmail-lmtpd.
The next test mail was still empty so i changed the database column to allow null as a workaround.

For the moment it works again as expected, at least on my private dbmail server. :-)

On the business server in the QC department i also changed the database column to allow null and will add the fix to dm_message.c in the next days when i am back in the office...

**Comment by alan-hicks** [comment] 2024-09-30 09:48
I'm adding some more debug code but I'm unable to compile as I'm getting the following error:
gmake[2]: *** No rule to make target 'check_dbmail_util_empty_envelope.c', needed by 'check_dbmail_util_empty_envelope.o'.  Stop.
Are there any other recent changes to check in?

**Comment by CozC** [comment] 2024-09-30 09:52
No, I was working on something related to checks, I guess that I missed something on a commit, the specified file is not ready yet. my bad. If you can please create an empty (minimum file) file and commit it and the I'll fill in the contents when is ready

**Comment by alan-hicks** [comment] 2024-09-30 10:34
Hi @mayrk ,

> i modified the src/dm_message.c file as shown in the commit, recompiled dbmail and restarted the service dbmail-lmtpd. The next test mail was still empty so i changed the database column to allow null as a workaround.

As a workaround maybe, but losing parts of an email isn't a good solution. I've just pushed additional tracing for parsing an email, it's minimal but should be able to identify what part is failing. The messages are "Init messsage size [%d]" "Messsage parse failed" and "Messsage parse part failed", you should be able to tell enough about the message and any difference between the size sent and received via lmtp or dbmail-deliver.

**Comment by alan-hicks** [comment] 2024-09-30 10:57
> If you can please create an empty (minimum file) file and commit it and the I'll fill in the contents when is ready

Okay, blank test added

**Comment by alan-hicks** [comment] 2024-09-30 11:32
Hi @mayrk , Let me know if you need the received message contents in the log, I'm reluctant to add it because of the verbosity but I'm keen to identify this bug.

**Comment by mayrk** [comment] 2024-09-30 13:46
As some messages can contain large file attachments too much details will blow up the log size ... :-/
Just as much as necessary to see what happens with some messages should be enough ... :-D

**Comment by alan-hicks** [comment] 2024-10-25 15:36
Is this issue fixed with recent updates or is it still outstanding?

**Comment by alan-hicks** [comment] 2024-12-04 17:05
Closing as no feedback and all tests pass.

**Closed by alan-hicks** 2024-12-04 17:05 UTC
