### ISSUE TITLE
Assertion failed: (physid), function dbmail_message_retrieve, file dm_message.c, line 1088.

### ISSUE THREAD

**Issue by autumnjolitz** [dbmail/dbmail#176] opened 2022-10-21 03:22 UTC
dbmail 3.2.6
postgresql 14.4

```
Oct 08 11:35:37 nyx dbmail-timsieved[536930]: [0x8028b2800] Error:[sort] sort_listextensions(+825): Sieve notify is not supported in this release.
Oct 08 11:48:25 nyx dbmail-timsieved[547131]: [0x8028b2800] Error:[sort] sort_listextensions(+825): Sieve notify is not supported in this release.
Oct 12 21:09:19 nyx dbmail-imapd[234102]: [0x8053c8260] Error:[imap] imap4(+786): no tag or command
Assertion failed: (physid), function dbmail_message_retrieve, file dm_message.c, line 1088.
```

How should I go about remediating this?

**Comment by CozC** [comment] 2022-10-21 04:11
salve,

So I see a couple of issues here:
- some issues related to sieve, you did not compiled with libsieve
- some issues with the email client (maybe)
- related to last message, I would, first, run dbmail-util to check for  
consistency of the data base. It seems you have message without the actual  
message. Each message is stored only once and it is referred to  
user/users, your message says you have a reference towards a missing  
physical message. run `dbmail-util -t`, for more information `dbmail-util  
--help`

Hope it helps


-- 
CC @gmail

**Comment by autumnjolitz** [comment] 2022-10-21 04:54
```
(cpython37) nyx:~$ dbmail-util -t
Choosing dry-run mode. No changes will be made at this time.

Checking DBMAIL message integrity...

Checking DBMAIL physmessage integrity...

Checking DBMAIL partlists integrity...
Ok. Found [0] unconnected partlists.

Checking DBMAIL mimeparts integrity...
Ok. Found [0] unconnected mimeparts.

Checking DBMAIL headernames integrity...
Ok. Found [11] unconnected headernames.

Checking DBMAIL headervalues integrity...
Ok. Found [0] unconnected headervalues.

Maintenance done. No errors found.
(cpython37) nyx:~$
```

**Comment by CozC** [comment] 2022-10-21 07:34
Well that's good news, you still have some issues but of no importance.
The log you have sent is is somehow lacking. I cannot understand if the  
assertion is linked to the message above. The problem is clear, the  
dbmail_imap has reached a point when it's asking for a physical message  
but that message does not exists.
I see only to start a debugging session and somehow send us the logs (or  
the log in the vicinity of the issue and make sure no personal information  
is displayed over there)
The log is quite expensive in terms of resources so one should be tread  
carefully when used.

Full logging can be started by updating the values bellow in dbmail.conf
`
file_logging_levels = 511
#
syslog_logging_levels = 511
`
and then restarting the dbmail-imapd daemon




-- 
CC @gmail

**Comment by autumnjolitz** [comment] 2022-10-22 04:39
Enabled for file logging (511)

**Comment by autumnjolitz** [comment] 2022-10-22 04:39
Now to wait for it to blow again

**Comment by alan-hicks** [comment] 2023-05-20 12:40
Closing as no further feedback.

**Closed by alan-hicks** 2023-05-20 12:40 UTC
